baseURL = "https://fypc.github.io/decripta.github.io/"
languageCode = "es-PE"
defaultContentLanguage = "es"
defaultContentLang = "es"
title = "decr!pta"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "FYP - All rights reserved"
enableEmoji = true
publishDir = "docs"
paginatePath = "blog"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="(aún) no está prohibido pensar"
  #mailchimp = "you can provide a mailchimp-link here"
  favicon = "/images/favicon.png"

[params.author]
  name = "John Doe"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/author.png"
  title = "John Doe"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu



